import { useMemo, useState } from 'react'
import { ArrowDownUp, Check, MapPin, PackageCheck, Search, ShoppingCart, Sparkles, Star, Bookmark, BookmarkCheck } from 'lucide-react'
import { motion } from 'framer-motion'
import type { MarketplaceListing } from '../../types'
import { Button } from '../common/Button'

const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 })

function ListingCard({ listing, onAdd, inCart, busy, saved, onToggleSaved }: { listing: MarketplaceListing; onAdd: (listing: MarketplaceListing) => void; inCart: boolean; busy: boolean; saved: boolean; onToggleSaved: (postId: string) => void }) {
  const discount = listing.originalPrice && listing.originalPrice > listing.price ? Math.round((1 - listing.price / listing.originalPrice) * 100) : 0
  const isVerifiedSeller = listing.seller.isCampusVerified || listing.seller.trustScore >= 80
  return <motion.article initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .3 }} className="overflow-hidden rounded-[16px] border border-[#e5eae6] bg-white transition-shadow hover:shadow-[0_14px_34px_rgba(30,55,43,.09)]">
    <div className="relative aspect-[1.38/1] overflow-hidden bg-[#edf1ed]">{listing.image && <img src={listing.image} alt={listing.title} className="size-full object-cover transition-transform duration-500 hover:scale-[1.035]" loading="lazy" />}{discount > 0 && <span className="absolute left-3 top-3 rounded-full bg-[#d94b3d] px-2.5 py-1 text-[10px] font-bold text-white">{discount}% below retail</span>}<button type="button" onClick={() => onToggleSaved(listing.id)} className="absolute right-3 top-3 inline-flex items-center gap-1 rounded-full bg-white/95 px-2.5 py-1.5 text-[10px] font-semibold text-[#243b31] shadow-sm transition hover:bg-white"><span>{saved ? <BookmarkCheck size={12} className="text-[#2f6d57]" /> : <Bookmark size={12} />}</span>{saved ? 'Saved' : 'Save'}</button><span className="absolute bottom-3 left-3 inline-flex items-center gap-1 rounded-lg bg-white/95 px-2 py-1 text-[10px] font-semibold text-[#68776e]"><MapPin size={11} />{listing.location}</span></div>
    <div className="p-4"><div className="mb-2 flex items-center justify-between gap-2"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-[#809087]">{listing.category}</span><span className="inline-flex items-center gap-1 text-[10px] font-semibold text-[#68806f]"><Star size={11} className="fill-[#c4d75d] text-[#a3b842]" />{Math.round(listing.seller.trustScore)} trust</span></div><div className="mb-1 flex items-center gap-2"><h2 className="font-display truncate text-base font-semibold text-[#263a31]">{listing.title}</h2>{isVerifiedSeller && <span className="rounded-full bg-[#eaf7ef] px-2 py-0.5 text-[9px] font-bold uppercase tracking-[.08em] text-[#2f6d57]">Verified</span>}</div><p className="mt-1.5 line-clamp-2 min-h-9 text-xs leading-[18px] text-[#7b8880]">{listing.description}</p><div className="mt-4 flex items-end justify-between gap-3"><div><p className="font-display text-[22px] font-bold leading-6 text-[#20382d]">{currency.format(listing.price)}</p>{listing.originalPrice && listing.originalPrice > listing.price && <p className="mt-1 text-[11px] text-[#95a099]"><span className="line-through">{currency.format(listing.originalPrice)}</span><span className="ml-1.5">retail</span></p>}</div><Button disabled={busy || listing.quantityAvailable < 1} onClick={() => onAdd(listing)} icon={inCart ? <Check size={15} /> : <ShoppingCart size={15} />} className="min-h-9 rounded-lg px-3 text-xs">{inCart ? 'Add another' : 'Add to cart'}</Button></div><div className="mt-3 flex items-center justify-between border-t border-[#eff2ef] pt-3 text-[10px] text-[#849189]"><span className="inline-flex items-center gap-1"><PackageCheck size={12} />{listing.quantityAvailable} available</span><span>{isVerifiedSeller ? 'Campus verified' : 'Seller'} · {listing.seller.displayName}</span></div></div>
  </motion.article>
}

export function StorePage({ listings, categories, error, cartHas, watchlistIds, onToggleSaved, onAdd, onOpenCart }: { listings: MarketplaceListing[]; categories: string[]; error: string; cartHas: (postId: string) => boolean; watchlistIds: string[]; onToggleSaved: (postId: string) => void; onAdd: (listing: MarketplaceListing) => void; onOpenCart: () => void }) {
  const [category, setCategory] = useState('All')
  const [search, setSearch] = useState('')
  const [sort, setSort] = useState<'featured' | 'price'>('featured')
  const [savedOnly, setSavedOnly] = useState(false)
  const categoryOptions = ['All', ...categories]
  const visible = useMemo(() => listings.filter((item) => (!savedOnly || watchlistIds.includes(item.id)) && (category === 'All' || item.category === category) && item.title.toLowerCase().includes(search.trim().toLowerCase())).sort((a, b) => sort === 'price' ? a.price - b.price : 0), [listings, category, search, sort, savedOnly, watchlistIds])

  return <section className="min-w-0"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.13em] text-[#698572]"><Sparkles size={13} />Buy it nearby</p><h1 className="font-display text-[32px] font-semibold leading-tight tracking-[-.03em] text-[#1c2b26]">Campus shop</h1><p className="mt-1.5 text-sm text-[#7a8781]">Fixed-price finds, ready for a local handoff.</p></div><Button variant="secondary" onClick={onOpenCart} icon={<ShoppingCart size={16} />}>View cart</Button></div>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row"><label className="relative min-w-0 flex-1"><Search size={15} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#8d9992]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search fixed-price listings" className="h-10 w-full rounded-xl border border-[#e4eae5] bg-white pl-10 pr-3 text-sm outline-none focus:border-[#9ab4a2]" /></label><button type="button" onClick={() => setSort((value) => value === 'featured' ? 'price' : 'featured')} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-[#e4eae5] bg-white px-3 text-xs font-semibold text-[#66766e]"><ArrowDownUp size={14} />{sort === 'price' ? 'Price: low to high' : 'Featured'}</button><button type="button" onClick={() => setSavedOnly((value) => !value)} className={`inline-flex h-10 items-center justify-center gap-2 rounded-xl px-3 text-xs font-semibold ${savedOnly ? 'bg-[#263b33] text-white' : 'border border-[#e4eae5] bg-white text-[#66766e]'}`}><Bookmark size={14} />{savedOnly ? 'Saved only' : 'Saved items'}</button></div>
    <div className="scrollbar-hidden mb-5 flex gap-2 overflow-x-auto pb-1">{categoryOptions.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${category === item ? 'bg-[#263b33] text-white' : 'border border-[#e3e9e4] bg-white text-[#73817a] hover:text-[#263b33]'}`}>{item}</button>)}</div>
    {error && <div role="alert" className="mb-4 rounded-xl border border-[#f0d7d2] bg-white px-4 py-3 text-sm text-[#a34237]">{error}</div>}
    {visible.length ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 2xl:grid-cols-3">{visible.map((listing) => <ListingCard key={listing.id} listing={listing} onAdd={onAdd} inCart={cartHas(listing.id)} busy={listing.quantityAvailable < 1} saved={watchlistIds.includes(listing.id)} onToggleSaved={onToggleSaved} />)}</div> : <div className="rounded-[18px] border border-dashed border-[#dce5de] bg-white px-6 py-16 text-center text-sm text-[#7a8781]">{error ? 'Shop items are temporarily unavailable.' : 'No fixed-price listings match this search.'}</div>}
  </section>
}
