import { motion } from 'framer-motion'
import { ArrowDownUp, ArrowUpRight, Bookmark, BookmarkCheck, MapPin, SlidersHorizontal, Sparkles } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { Auction } from '../../types'
import { useCountdown } from '../../hooks/useCountdown'
import { Badge, LiveBadge } from '../common/Badge'
import { IconButton } from '../common/Button'
import { useCurrency } from '../../lib/CurrencyContext'

function TimeLeft({ endsAt }: { endsAt: string }) {
  const time = useCountdown(endsAt)
  const label = time.expired ? 'Ended' : time.days > 0 ? `${time.days}d ${time.hours}h` : `${String(time.hours).padStart(2, '0')}:${String(time.minutes).padStart(2, '0')}:${String(time.seconds).padStart(2, '0')}`
  return <span className="tabular-nums text-xs font-semibold text-white">{label}</span>
}

function AuctionCard({ auction, index, onOpen, watchlisted, saving, watchlistLoading, canWatch, onToggleWatchlist }: { auction: Auction; index: number; onOpen: (auction: Auction) => void; watchlisted: boolean; saving: boolean; watchlistLoading: boolean; canWatch: boolean; onToggleWatchlist: (auction: Auction) => void }) {
  const { formatUsd } = useCurrency()
  return <motion.article className="group overflow-hidden rounded-[18px] border border-[#e6ebe7] bg-white transition-shadow hover:shadow-[0_16px_40px_rgba(32,54,45,.11)]" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .35, delay: index * .055 }}>
    <div className="relative aspect-[1.4/1] overflow-hidden bg-[#e9eeea]"><button type="button" onClick={() => onOpen(auction)} aria-label={`Open ${auction.title} auction`} className="block size-full text-left">{auction.image && <img src={auction.image} alt={auction.title} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.04]" loading={index > 2 ? 'lazy' : 'eager'} />}<div className="pointer-events-none absolute left-3 top-3 flex gap-2"><LiveBadge />{auction.noReserve && <Badge className="bg-white/95 text-[#526321]">No reserve</Badge>}</div><span className="pointer-events-none absolute bottom-3 right-3 rounded-lg bg-[#17211e]/85 px-2.5 py-1.5 text-white backdrop-blur"><TimeLeft endsAt={auction.endsAt} /></span></button>{canWatch && <button type="button" onClick={() => onToggleWatchlist(auction)} disabled={saving || watchlistLoading} aria-label={watchlisted ? `Remove ${auction.title} from watchlist` : `Add ${auction.title} to watchlist`} title={watchlisted ? 'Remove from watchlist' : 'Add to watchlist'} className="absolute right-3 top-3 grid size-10 place-items-center rounded-full bg-white/95 text-[#294638] shadow-sm transition hover:bg-white disabled:opacity-50">{watchlisted ? <BookmarkCheck size={18} /> : <Bookmark size={18} />}</button>}</div>
    <button type="button" onClick={() => onOpen(auction)} className="block w-full p-4 text-left"><div className="mb-2 flex items-center justify-between gap-3"><span className="truncate text-[11px] font-semibold uppercase tracking-[.1em] text-[#82908a]">{auction.category}</span><span className="flex shrink-0 items-center gap-1 text-[11px] text-[#87938e]"><MapPin size={11} />{auction.location}</span></div><h3 className="font-display truncate text-[17px] font-semibold text-[#1e302a]">{auction.title}</h3><div className="mt-4 flex items-end justify-between border-t border-[#edf0ed] pt-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.09em] text-[#87938e]">Current bid</p><p key={auction.currentHighestBid} className="font-display ticker-flash mt-0.5 text-[21px] font-bold text-[#1e302a]">{formatUsd(auction.currentHighestBid, 0)}</p></div><span className="mb-1 flex items-center gap-1 text-xs font-semibold text-[#547065]">{auction.bids.length} bids <ArrowUpRight size={14} /></span></div></button>
  </motion.article>
}

export function GlobalFeed({ auctions, categories, watchlistIds, savingWatchlistId, watchlistLoading, currentUserId, onOpen, onToggleWatchlist }: { auctions: Auction[]; categories: string[]; watchlistIds: string[]; savingWatchlistId: string | null; watchlistLoading: boolean; currentUserId: string; onOpen: (auction: Auction) => void; onToggleWatchlist: (auction: Auction) => void; session?: unknown; emailConfirmed?: boolean; onRequestSignIn?: () => void }) {
  const [category, setCategory] = useState('For you')
  const [sort, setSort] = useState<'ending' | 'recent'>('ending')
  const categoryOptions = ['For you', 'All', ...categories]
  const visible = useMemo(() => auctions.filter((auction) => auction.status === 'ACTIVE' && (category === 'For you' || category === 'All' || auction.category === category)).sort((a, b) => sort === 'ending' ? new Date(a.endsAt).getTime() - new Date(b.endsAt).getTime() : b.bids.length - a.bids.length), [auctions, category, sort])

  return <section className="min-w-0"><div className="mb-6 flex items-end justify-between gap-3"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-[#628174]"><Sparkles size={13} />The campus edit</div><div className="flex items-center gap-2"><button type="button" className="hidden rounded-full border border-[#dfe8e1] bg-[#f3faf3] px-3 py-2 text-[10px] font-semibold uppercase tracking-[.12em] text-[#35614d] sm:inline-flex sm:items-center sm:gap-2"><Sparkles size={12} />Add bid</button><IconButton label={`Sort by ${sort === 'ending' ? 'most bids' : 'ending soon'}`} onClick={() => setSort((value) => value === 'ending' ? 'recent' : 'ending')} className="border border-[#e1e8e2] bg-white"><ArrowDownUp size={17} /></IconButton></div></div>
    <div className="scrollbar-hidden mb-5 flex items-center gap-2 overflow-x-auto pb-1">{categoryOptions.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={`inline-flex w-max flex-none whitespace-nowrap rounded-full border px-3.5 py-2 text-xs font-semibold transition-colors ${category === item ? 'border-[#263b33] bg-[#263b33] text-white' : 'border-[#e3e9e4] bg-white text-[#73817a] hover:border-[#b9c8bd] hover:text-[#263b33]'}`}>{item}</button>)}<span className="ml-auto hidden items-center gap-1 text-[11px] text-[#89968f] sm:flex"><SlidersHorizontal size={13} />Sorted by {sort === 'ending' ? 'ending soon' : 'most bids'}</span></div>
    {visible.length ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 2xl:grid-cols-3">{visible.map((auction, index) => <AuctionCard key={auction.id} auction={auction} index={index} onOpen={onOpen} watchlisted={watchlistIds.includes(auction.id)} saving={savingWatchlistId === auction.id} watchlistLoading={watchlistLoading} canWatch={auction.sellerId !== currentUserId} onToggleWatchlist={onToggleWatchlist} />)}</div> : <div className="rounded-[18px] border border-dashed border-[#dce5de] bg-white px-6 py-16 text-center text-sm text-[#7a8781]">Nothing is bidding in this category right now.</div>}</section>
}
