import { useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { ArrowUpRight, BadgeCheck, CircleDollarSign, Clock3, ImagePlus, PackageCheck, ShieldAlert } from 'lucide-react'
import type { Auction, MarketplaceListing, Verdict } from '../../types'
import { TrustScoreBadge } from '../common/TrustScoreBadge'
import { Button } from '../common/Button'
import { CreateListingModal } from './CreateListingModal'
import { SellerVerdictModal } from './SellerVerdictModal'

const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })

export function SellerDashboard({ auctions, userId, trustScore, completedAuctions, session, emailConfirmed, ownListings, onRequestSignIn, onListingCreated, onVerdict, onNotice }: { auctions: Auction[]; userId?: string; trustScore: number; completedAuctions: number; session: Session | null; emailConfirmed: boolean; ownListings: MarketplaceListing[]; onRequestSignIn: () => void; onListingCreated: (listing: MarketplaceListing) => void; onVerdict: (auction: Auction, decision: Verdict) => Promise<void>; onNotice: (message: string, kind?: 'success' | 'error') => void }) {
  const [selected, setSelected] = useState<Auction | null>(null)
  const [createListingOpen, setCreateListingOpen] = useState(false)
  const pending = auctions.filter((auction) => auction.status === 'PENDING_APPROVAL' && (!userId || auction.sellerId === userId))
  const active = auctions.filter((auction) => auction.status === 'ACTIVE' && (!userId || auction.sellerId === userId))
  const startListing = () => {
    if (!session) {
      onRequestSignIn()
      return
    }
    if (!emailConfirmed) {
      onNotice('Confirm your email before adding products.', 'error')
      return
    }
    setCreateListingOpen(true)
  }
  return <section className="min-w-0 enter-up"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.12em] text-[#628174]">Your workspace</p><h1 className="font-display text-[32px] font-semibold leading-tight tracking-[-.03em] text-[#1c2b26]">Seller dashboard</h1><p className="mt-1.5 text-sm text-[#7a8781]">Your products, decisions, and trust record.</p></div><Button onClick={startListing} icon={<ImagePlus size={16} />}>Add product</Button></div>
    <div className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-3"><div className="rounded-[16px] border border-[#e4eae5] bg-white p-4"><div className="flex items-center justify-between text-xs font-medium text-[#819087]"><span>Seller trust</span><ShieldAlert size={15} /></div><p className="font-display mt-2 text-3xl font-bold text-[#294339]">{Math.round(trustScore)}<span className="text-base font-semibold text-[#91a099]"> / 100</span></p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#eef2ed]"><div className="h-full rounded-full bg-[#6c9a75]" style={{ width: `${Math.max(0, Math.min(100, trustScore))}%` }} /></div></div><div className="rounded-[16px] border border-[#e4eae5] bg-white p-4"><div className="flex items-center justify-between text-xs font-medium text-[#819087]"><span>Active listings</span><CircleDollarSign size={15} /></div><p className="font-display mt-2 text-3xl font-bold text-[#294339]">{active.length}</p><p className="mt-1 text-[11px] text-[#91a099]">Currently accepting bids</p></div><div className="rounded-[16px] border border-[#e4eae5] bg-white p-4"><div className="flex items-center justify-between text-xs font-medium text-[#819087]"><span>Completed sales</span><PackageCheck size={15} /></div><p className="font-display mt-2 text-3xl font-bold text-[#294339]">{completedAuctions}</p><p className="mt-1 text-[11px] text-[#91a099]">Trust grows with follow-through</p></div></div>
    {pending.length > 0 && <div className="mb-6 rounded-[18px] border border-[#efdec0] bg-[#fffaf0] p-5"><div className="mb-4 flex items-center gap-2"><Clock3 size={17} className="text-[#ad7b35]" /><h2 className="font-display text-base font-semibold text-[#4a3c25]">Your decision needed</h2><span className="rounded-full bg-[#f4e7c9] px-2 py-0.5 text-[10px] font-bold text-[#8d6834]">{pending.length}</span></div><div className="space-y-3">{pending.map((auction) => <div key={auction.id} className="flex flex-col gap-4 rounded-xl border border-[#f0e7d6] bg-white p-3 sm:flex-row sm:items-center"><img src={auction.image} alt="" className="h-24 w-full rounded-lg object-cover sm:size-20" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#35473f]">{auction.title}</p><p className="mt-1 text-xs text-[#87938d]">High bidder: {auction.bids[0]?.bidder.displayName ?? 'Campus bidder'}</p><p className="font-display mt-1 text-lg font-bold text-[#354b3d]">{currency.format(auction.currentHighestBid)}</p></div><Button onClick={() => setSelected(auction)} icon={<ArrowUpRight size={15} />} className="shrink-0">Review verdict</Button></div>)}</div></div>}
    <div className="overflow-hidden rounded-[18px] border border-[#e4eae5] bg-white"><div className="flex items-center justify-between border-b border-[#edf0ed] px-5 py-4"><div><h2 className="font-display text-base font-semibold text-[#263b33]">Active listings</h2><p className="mt-0.5 text-xs text-[#87938d]">Live public rooms tied to your seller profile.</p></div><span className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#628174]"><BadgeCheck size={14} />Accountability on</span></div>{active.length ? <div className="divide-y divide-[#f0f2f0]">{active.map((auction) => <div key={auction.id} className="flex items-center gap-3 px-5 py-4"><img src={auction.image} alt="" className="size-12 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#35473f]">{auction.title}</p><p className="mt-1 text-xs text-[#87938d]">{auction.bids.length} bids · ending {new Date(auction.endsAt).toLocaleString([], { hour: 'numeric', minute: '2-digit' })}</p></div><div className="text-right"><p className="font-display text-base font-bold text-[#354b3d]">{currency.format(auction.currentHighestBid)}</p><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#7b8d82]">Current bid</p></div></div>)}</div> : <div className="px-5 py-10 text-center text-sm text-[#89958f]">No active listings to show.</div>}</div>
    <div className="mt-6 overflow-hidden rounded-[18px] border border-[#e4eae5] bg-white"><div className="border-b border-[#edf0ed] px-5 py-4"><h2 className="font-display text-base font-semibold text-[#263b33]">Your products</h2><p className="mt-0.5 text-xs text-[#87938d]">Items you have listed for campus buyers.</p></div>{ownListings.length ? <div className="grid grid-cols-1 divide-y divide-[#f0f2f0] sm:grid-cols-2 sm:divide-y-0">{ownListings.map((listing) => <article key={listing.id} className="flex min-w-0 gap-3 p-4"><img src={listing.image || 'https://images.unsplash.com/photo-1493857671505-72967e2e2760?auto=format&fit=crop&w=240&q=80'} alt={listing.title} className="size-16 shrink-0 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#35473f]">{listing.title}</p><p className="mt-1 truncate text-xs text-[#87938d]">{listing.category} · {listing.quantityAvailable} available</p><p className="font-display mt-1 text-base font-bold text-[#354b3d]">{currency.format(listing.price)}</p></div></article>)}</div> : <div className="px-5 py-8 text-center text-sm text-[#89958f]">You have not added any products yet.</div>}</div>
    <div className="mt-4 flex items-start gap-2 text-[11px] leading-5 text-[#87938d]"><ShieldAlert size={14} className="mt-0.5 shrink-0" />Rejecting a winning bid reduces trust by 20 points and freezes that listing. Only reject when you cannot complete the sale.</div>
    <CreateListingModal open={createListingOpen} onClose={() => setCreateListingOpen(false)} session={session} onCreated={onListingCreated} />
    <SellerVerdictModal auction={selected} open={Boolean(selected)} onClose={() => setSelected(null)} onSubmit={async (decision) => { if (!selected) return; await onVerdict(selected, decision); onNotice(decision === 'ACCEPT' ? 'Sale confirmed. Your seller trust improved.' : 'Bid rejected. The listing is frozen and your trust score changed.'); setSelected(null) }} />
  </section>
}

export function DashboardTrust({ score, count }: { score: number; count: number }) { return <TrustScoreBadge score={score} completedAuctions={count} /> }
